import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Homepage from 'components/Homepage'
import Partners from 'components/Partners'
import Accommodations from 'Residencies/Accommodations'
import Char from 'Residencies/Char'
import Contact from 'Residencies/Contact'
import Started from 'Residencies/Started'
import SkeletonLoading from 'Sekeleton'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Realstez</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main>
        <Homepage/>
        <Partners/>
        <Accommodations/>
        <Char/>
        <Contact/>
        <Started/>
      
      
      </main>
    </>
  )
}
